"""empty message

Revision ID: 0db86b1a59c5
Revises: c03f7cac988c
Create Date: 2022-05-11 22:26:55.237590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db86b1a59c5'
down_revision = 'c03f7cac988c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pokemon', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='unique')
    # ### end Alembic commands ###
