"""empty message

Revision ID: 7d164a753f5c
Revises: 0db86b1a59c5
Create Date: 2022-05-11 22:33:38.448861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d164a753f5c'
down_revision = '0db86b1a59c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pokemon_name_key', 'pokemon', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pokemon_name_key', 'pokemon', ['name'])
    # ### end Alembic commands ###
