"""empty message

Revision ID: c03f7cac988c
Revises: ec0a05d59a48
Create Date: 2022-05-11 00:29:28.951877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03f7cac988c'
down_revision = 'ec0a05d59a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('sprite2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'sprite2')
    # ### end Alembic commands ###
