"""empty message

Revision ID: ec0a05d59a48
Revises: a351be4533f0
Create Date: 2022-05-10 03:32:45.299614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0a05d59a48'
down_revision = 'a351be4533f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('base_exp', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('sprite', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('attack', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('defense', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'defense')
    op.drop_column('pokemon', 'attack')
    op.drop_column('pokemon', 'sprite')
    op.drop_column('pokemon', 'base_exp')
    op.drop_column('pokemon', 'ability')
    # ### end Alembic commands ###
